In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
import sys
!{sys.executable} -m pip install pandas numpy matplotlib scikit-learn

Requirement already satisfied: pandas in c:\users\yaaar\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\yaaar\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: matplotlib in c:\users\yaaar\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: scikit-learn in c:\users\yaaar\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yaaar\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yaaar\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yaaar\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\yaaar\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\yaaar\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\yaaar\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\yaaar\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\yaaar\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\yaaar\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\yaaar\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: scipy>=1.6.0 in c:\users\yaaar\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\yaaar\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\yaaar\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\yaaar\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
df=pd.read_csv('height-weight.csv')
df.head()

   Weight  Height
0      45     120
1      58     135
2      48     123
3      60     145
4      70     160

In [4]:
plt.scatter(df['Weight'],df['Height'])
plt.xlabel("Weight")
plt.ylabel("Height")

Text(0, 0.5, 'Height')

In [5]:
## divide our dataset into independent and dependent edatures
X=df[['Weight']] ##independent feature
y=df['Height'] ##dependent feature

In [6]:
## Train test split
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [8]:
X.shape

(23, 1)

In [9]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((18, 1), (5, 1), (18,), (5,))

In [10]:
## standardize the dataset Train independent data
from sklearn.preprocessing import StandardScaler

In [11]:
scaler=StandardScaler()

In [12]:
X_train.head()

    Weight
12     105
1       58
13     100
5       78
2       48

In [13]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
plt.scatter(X_train,y_train)

In [14]:
## Train the Simple Linear Regression Model
from sklearn.linear_model import LinearRegression

In [15]:
regressor=LinearRegression()

In [16]:
regressor.fit(X_train,y_train)

LinearRegression()

In [17]:
print("The slope or coefficient of weight is ",regressor.coef_)
print("Intercept:",regressor.intercept_)

The slope or coefficient of weight is  [17.03440872]
Intercept: 157.5

In [18]:
plt.scatter(X_train,y_train)
plt.plot(X_train,regressor.predict(X_train),'r')

In [ ]:
plt.scatter(X_train,y_train)
plt.plot(X_train,regressor.predict(X_train),'r')